server:
  port: 8081
spring:
  config:
    activate:
      on-profile: test
openapi:
  service:
    api-docs: api-service
    server: http://localhost:${server.port}
    title: Server test
    version: 1.0.0